### PR TITLE
Set `execution_state` when executing a cell

### PR DESCRIPTION
**Pull request by krassowski**
Necessary but not sufficient to fix https://github.com/datalayer/jupyter-server-nbmodel/issues/13

Still needs:
- https://github.com/jupyter-server/jupyter_ydoc/pull/259
- https://github.com/jupyterlab/jupyterlab/pull/16651

### CODE REVIEW

**Comment by krassowski** [comment]
The test failure appears unrelated as it is also failing on `main` branch ([here](https://github.com/datalayer/jupyter-server-nbmodel/actions/runs/10145634801/job/28051798374)).

**Comment by krassowski** [comment]
The upstream PRs are all merged now :)

**Comment by krassowski** [comment]
@echarles / @fcollonval any thoughts here?

**Comment by echarles** [comment]
@krassowski Thank you for the ping. We have been running on many different tracks and will be able to take this back later next week only.

**Comment by krassowski** [comment]
I understand, thank you for leading this! Let me know how I can help.

**Review by fcollonval — APPROVED** [review]
Thanks @krassowski

**Pull request merged**
