### PR TITLE
Multiple enhancements

### LINKED ISSUE #7: Should code be executed asynchronously in RTC mode?
### Problem

https://github.com/datalayer/jupyter-server-nbmodel/blob/b122d68e2c9608f24201aa757a47ea922147825d/jupyter_server_nbmodel/handlers.py#L125-L131

I've found that current implementations where cell takes longer to execute can lead to http request timeouts (especially behind some reverse proxies), and it's difficult for the front-end to determine if the request to execute the code was successfully sent.

### Proposed Solution

1. We can simply support asynchronous mode: do execute and safe in an asyncio.Task.
2. Maybe we need an optimistic lock to prevent racing  when concurrent write to the ynotebook.

### PR DESCRIPTION
**Pull request by fcollonval**
- Use a execution stack to avoid trouble for long running cells (fixes #7 )
- Concatenate stream outputs
- Support clear_output
- Attempt to support stdin (not working currently)

### CODE REVIEW

**Comment by Wh1isper** [comment]
Thanks for the mention.

For stdin issue, it seems that the problem is the timing of the stdin input?

In my understanding, with the help of the front-end, the user should be able to input stdin via front-end. Without a front-end or any interaction page (which can be something like a terminal), it might be hard to support this feature.

**Comment by fcollonval** [comment]
> For stdin issue, it seems that the problem is the timing of the stdin input?

Not sure to understand. But the main problem is that we have no idea ahead of execution if a snippet will prompt for stdin. So the execution request caller should interrogate the server or be notified when such event occurs.
For now, the solution is to poll a end point to determine the status of the execution - in process, finished or waiting for an input.

> Without a front-end or any interaction page (which can be something like a terminal), it might be hard to support this feature.

With the above mentioned mechanism, any case is supported. Although how to prompt for user input is gonna changed depending on the front end.

**Comment by Wh1isper** [comment]
> But the main problem is that we have no idea ahead of execution if a snippet will prompt for stdin.

Yes, that's what I meant. Actually it was this PR that reminded me of it. (Probably because I've basically never used inputs in Jupyter..)

> For now, the solution is to poll a end point to determine the status of the execution - in process, finished or waiting for an input.

And it depends on when the client (front-end) sends, which means that the front-end still needs to listen to the websocket and display the input prompt box. 🤔

**Comment by fcollonval** [comment]
> And it depends on when the client (front-end) sends, which means that the front-end still needs to listen to the websocket and display the input prompt box. 🤔

@Wh1isper It requires fetching a status endpoint. See that sequence diagram: https://github.com/datalayer/jupyter-server-nbmodel?tab=readme-ov-file#with-input-case

You can see an updated demo [there](https://github.com/jupyter-server/jupyter_server/issues/900#issuecomment-2110202144)

**Comment by Wh1isper** [comment]
Nice

**Pull request merged**
